# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the bin/rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
User.create!(user_name: "Black Chickadee", email:"blackadee@gmail.com", password_digest: "123456789")
User.create!(user_name: "Grackle Lee", email: "grackle123@gmail.com", password_digest: "123456789")
User.create!(user_name: "Common Staff", email: "staff123@gmail.com", password_digest: "123456789")
User.create!(user_name: "Mourning Love", email: "mourninglove@gmail.com", password_digest: "123456789")

Pet.create!(name: "Black-Capped Chickadee", image: "https://thumbs.nosto.com/quick/magento-f5b2bba1/8/739/b029781e52786ae998d443aaabc21eeb41e1c1071c987fbc843bb5c47fd1b1e0a/A.jpg", user_id: 1)
Pet.create!(name: "Grackle", image: "https://thumbs.nosto.com/quick/magento-f5b2bba1/8/1168/35cd82d17184164089a6c71ff97324a272d201f23745b6daf3967cd7aa55e836a/A.jpg", user_id: 1)
Pet.create!(name: "Common Starling", image: "https://thumbs.nosto.com/quick/magento-f5b2bba1/8/978/e592f527bb190544899ab4ba25565461079b49723ba1a2d54e5a8f768804459aa/A.jpg", user_id: 2)
Pet.create!(name: "Mourning Dove", image: "https://thumbs.nosto.com/quick/magento-f5b2bba1/8/948/1dafde5e309ab84921f74bb89ff0682e528252d109505e7cfd0bb96bdbd382fba/A.jpg", user_id: 2)
Pet.create!(name: "Black-Capped Chickadee", image: "https://thumbs.nosto.com/quick/magento-f5b2bba1/8/981/15c821d68a4f650b78375f3ddf34ad3cfe713cb72740007af9ea2169810a3f70a/A.jpg", user_id: 3)
Pet.create!(name: "Grackle", image: "https://thumbs.nosto.com/quick/magento-f5b2bba1/8/1143/76972987a5aa61935674dd3c860a396ff6fe80ede851e4413af554bbe10706eca/A.jpg", user_id: 3)
Pet.create!(name: "Common Starling", image: "https://thumbs.nosto.com/quick/magento-f5b2bba1/8/829/9c299d4be3e9812a603be15170a7362937dbdc6faba932fd50a9c0f12a2c5578a/A.jpg", user_id: 4)
Pet.create!(name: "Mourning Dove", image: "https://thumbs.nosto.com/quick/magento-f5b2bba1/8/882/ebeef92771db8103fe5951f1f6a4eb1910b9242f5a69cc277b480782e615c71fa/A.jpg", user_id: 4)

Comment.create!(content: "Mourning Love Black-Capped Chickadee Grackle Common Starling Mourning Dove Black-Capped Chickadee Grackle Common Starling Mourning Dove Black-Capped Chickadee Grackle Common Starling Mourning Dove ", user_id: 1, pet_id: 1)
Comment.create!(content: "Mourning Love Black-Capped Chickadee Grackle Common Starling Mourning Dove Black-Capped Chickadee Grackle Common Starling Mourning Dove Black-Capped Chickadee Grackle Common Starling Mourning Dove ", user_id: 1, pet_id: 2)
Comment.create!(content: "Mourning Love Black-Capped Chickadee Grackle Common Starling Mourning Dove Black-Capped Chickadee Grackle Common Starling Mourning Dove Black-Capped Chickadee Grackle Common Starling Mourning Dove ", user_id: 1, pet_id: 3)
Comment.create!(content: "Mourning Love Black-Capped Chickadee Grackle Common Starling Mourning Dove Black-Capped Chickadee Grackle Common Starling Mourning Dove Black-Capped Chickadee Grackle Common Starling Mourning Dove ", user_id: 1, pet_id: 4)
Comment.create!(content: "Mourning Love Black-Capped Chickadee Grackle Common Starling Mourning Dove Black-Capped Chickadee Grackle Common Starling Mourning Dove Black-Capped Chickadee Grackle Common Starling Mourning Dove ", user_id: 1, pet_id: 5)
Comment.create!(content: "Mourning Love Black-Capped Chickadee Grackle Common Starling Mourning Dove Black-Capped Chickadee Grackle Common Starling Mourning Dove Black-Capped Chickadee Grackle Common Starling Mourning Dove ", user_id: 1, pet_id: 6)
Comment.create!(content: "Mourning Love Black-Capped Chickadee Grackle Common Starling Mourning Dove Black-Capped Chickadee Grackle Common Starling Mourning Dove Black-Capped Chickadee Grackle Common Starling Mourning Dove ", user_id: 1, pet_id: 7)
Comment.create!(content: "Mourning Love Black-Capped Chickadee Grackle Common Starling Mourning Dove Black-Capped Chickadee Grackle Common Starling Mourning Dove Black-Capped Chickadee Grackle Common Starling Mourning Dove ", user_id: 1, pet_id: 8)
Comment.create!(content: "Mourning Love Black-Capped Chickadee Grackle Common Starling Mourning Dove Black-Capped Chickadee Grackle Common Starling Mourning Dove Black-Capped Chickadee Grackle Common Starling Mourning Dove ", user_id: 2, pet_id: 1)
Comment.create!(content: "Mourning Love Black-Capped Chickadee Grackle Common Starling Mourning Dove Black-Capped Chickadee Grackle Common Starling Mourning Dove Black-Capped Chickadee Grackle Common Starling Mourning Dove ", user_id: 2, pet_id: 2)
Comment.create!(content: "Mourning Love Black-Capped Chickadee Grackle Common Starling Mourning Dove Black-Capped Chickadee Grackle Common Starling Mourning Dove Black-Capped Chickadee Grackle Common Starling Mourning Dove ", user_id: 2, pet_id: 3)
Comment.create!(content: "Mourning Love Black-Capped Chickadee Grackle Common Starling Mourning Dove Black-Capped Chickadee Grackle Common Starling Mourning Dove Black-Capped Chickadee Grackle Common Starling Mourning Dove ", user_id: 2, pet_id: 4)
Comment.create!(content: "Mourning Love Black-Capped Chickadee Grackle Common Starling Mourning Dove Black-Capped Chickadee Grackle Common Starling Mourning Dove Black-Capped Chickadee Grackle Common Starling Mourning Dove ", user_id: 2, pet_id: 5)
Comment.create!(content: "Mourning Love Black-Capped Chickadee Grackle Common Starling Mourning Dove Black-Capped Chickadee Grackle Common Starling Mourning Dove Black-Capped Chickadee Grackle Common Starling Mourning Dove ", user_id: 2, pet_id: 6)
Comment.create!(content: "Mourning Love Black-Capped Chickadee Grackle Common Starling Mourning Dove Black-Capped Chickadee Grackle Common Starling Mourning Dove Black-Capped Chickadee Grackle Common Starling Mourning Dove ", user_id: 2, pet_id: 7)
Comment.create!(content: "Mourning Love Black-Capped Chickadee Grackle Common Starling Mourning Dove Black-Capped Chickadee Grackle Common Starling Mourning Dove Black-Capped Chickadee Grackle Common Starling Mourning Dove ", user_id: 2, pet_id: 8)
Comment.create!(content: "Mourning Love Black-Capped Chickadee Grackle Common Starling Mourning Dove Black-Capped Chickadee Grackle Common Starling Mourning Dove Black-Capped Chickadee Grackle Common Starling Mourning Dove ", user_id: 3, pet_id: 1)
Comment.create!(content: "Mourning Love Black-Capped Chickadee Grackle Common Starling Mourning Dove Black-Capped Chickadee Grackle Common Starling Mourning Dove Black-Capped Chickadee Grackle Common Starling Mourning Dove ", user_id: 3, pet_id: 2)
Comment.create!(content: "Mourning Love Black-Capped Chickadee Grackle Common Starling Mourning Dove Black-Capped Chickadee Grackle Common Starling Mourning Dove Black-Capped Chickadee Grackle Common Starling Mourning Dove ", user_id: 3, pet_id: 3)
Comment.create!(content: "Mourning Love Black-Capped Chickadee Grackle Common Starling Mourning Dove Black-Capped Chickadee Grackle Common Starling Mourning Dove Black-Capped Chickadee Grackle Common Starling Mourning Dove ", user_id: 3, pet_id: 4)
Comment.create!(content: "Mourning Love Black-Capped Chickadee Grackle Common Starling Mourning Dove Black-Capped Chickadee Grackle Common Starling Mourning Dove Black-Capped Chickadee Grackle Common Starling Mourning Dove ", user_id: 3, pet_id: 5)
Comment.create!(content: "Mourning Love Black-Capped Chickadee Grackle Common Starling Mourning Dove Black-Capped Chickadee Grackle Common Starling Mourning Dove Black-Capped Chickadee Grackle Common Starling Mourning Dove ", user_id: 3, pet_id: 6)
Comment.create!(content: "Mourning Love Black-Capped Chickadee Grackle Common Starling Mourning Dove Black-Capped Chickadee Grackle Common Starling Mourning Dove Black-Capped Chickadee Grackle Common Starling Mourning Dove ", user_id: 3, pet_id: 7)
Comment.create!(content: "Mourning Love Black-Capped Chickadee Grackle Common Starling Mourning Dove Black-Capped Chickadee Grackle Common Starling Mourning Dove Black-Capped Chickadee Grackle Common Starling Mourning Dove ", user_id: 3, pet_id: 8)
Comment.create!(content: "Mourning Love Black-Capped Chickadee Grackle Common Starling Mourning Dove Black-Capped Chickadee Grackle Common Starling Mourning Dove Black-Capped Chickadee Grackle Common Starling Mourning Dove ", user_id: 4, pet_id: 1)
Comment.create!(content: "Mourning Love Black-Capped Chickadee Grackle Common Starling Mourning Dove Black-Capped Chickadee Grackle Common Starling Mourning Dove Black-Capped Chickadee Grackle Common Starling Mourning Dove ", user_id: 4, pet_id: 2)
Comment.create!(content: "Mourning Love Black-Capped Chickadee Grackle Common Starling Mourning Dove Black-Capped Chickadee Grackle Common Starling Mourning Dove Black-Capped Chickadee Grackle Common Starling Mourning Dove ", user_id: 4, pet_id: 3)
Comment.create!(content: "Mourning Love Black-Capped Chickadee Grackle Common Starling Mourning Dove Black-Capped Chickadee Grackle Common Starling Mourning Dove Black-Capped Chickadee Grackle Common Starling Mourning Dove ", user_id: 4, pet_id: 4)
Comment.create!(content: "Mourning Love Black-Capped Chickadee Grackle Common Starling Mourning Dove Black-Capped Chickadee Grackle Common Starling Mourning Dove Black-Capped Chickadee Grackle Common Starling Mourning Dove ", user_id: 4, pet_id: 5)
Comment.create!(content: "Mourning Love Black-Capped Chickadee Grackle Common Starling Mourning Dove Black-Capped Chickadee Grackle Common Starling Mourning Dove Black-Capped Chickadee Grackle Common Starling Mourning Dove ", user_id: 4, pet_id: 6)
Comment.create!(content: "Mourning Love Black-Capped Chickadee Grackle Common Starling Mourning Dove Black-Capped Chickadee Grackle Common Starling Mourning Dove Black-Capped Chickadee Grackle Common Starling Mourning Dove ", user_id: 4, pet_id: 7)
Comment.create!(content: "Mourning Love Black-Capped Chickadee Grackle Common Starling Mourning Dove Black-Capped Chickadee Grackle Common Starling Mourning Dove Black-Capped Chickadee Grackle Common Starling Mourning Dove ", user_id: 4, pet_id: 8)

Rating.create!(point: 4, user_id: 1, pet_id: 1)
Rating.create!(point: 4, user_id: 1, pet_id: 2)
Rating.create!(point: 4, user_id: 1, pet_id: 3)
Rating.create!(point: 4, user_id: 1, pet_id: 4)
Rating.create!(point: 4, user_id: 1, pet_id: 5)
Rating.create!(point: 4, user_id: 1, pet_id: 6)
Rating.create!(point: 4, user_id: 1, pet_id: 7)
Rating.create!(point: 4, user_id: 1, pet_id: 8)
Rating.create!(point: 4, user_id: 2, pet_id: 1)
Rating.create!(point: 4, user_id: 2, pet_id: 2)
Rating.create!(point: 4, user_id: 2, pet_id: 3)
Rating.create!(point: 4, user_id: 2, pet_id: 4)
Rating.create!(point: 4, user_id: 2, pet_id: 5)
Rating.create!(point: 4, user_id: 2, pet_id: 6)
Rating.create!(point: 4, user_id: 2, pet_id: 7)
Rating.create!(point: 4, user_id: 2, pet_id: 8)
Rating.create!(point: 4, user_id: 3, pet_id: 1)
Rating.create!(point: 4, user_id: 3, pet_id: 2)
Rating.create!(point: 4, user_id: 3, pet_id: 3)
Rating.create!(point: 4, user_id: 3, pet_id: 4)
Rating.create!(point: 4, user_id: 3, pet_id: 5)
Rating.create!(point: 4, user_id: 3, pet_id: 6)
Rating.create!(point: 4, user_id: 3, pet_id: 7)
Rating.create!(point: 4, user_id: 3, pet_id: 8)
Rating.create!(point: 4, user_id: 4, pet_id: 1)
Rating.create!(point: 4, user_id: 4, pet_id: 2)
Rating.create!(point: 4, user_id: 4, pet_id: 3)
Rating.create!(point: 4, user_id: 4, pet_id: 4)
Rating.create!(point: 4, user_id: 4, pet_id: 5)
Rating.create!(point: 4, user_id: 4, pet_id: 6)
Rating.create!(point: 4, user_id: 4, pet_id: 7)
Rating.create!(point: 4, user_id: 4, pet_id: 8)